### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by KrypticCoconut** [125K/PwrDeauther#4]
Hello i just downloaded this and it doesn't seem to work, after it says `starting now`, it doesn't work, neither does it put my WiFi card on monitoring mode :P
Thanks!

**Comment by adamff-dev** [comment]
try ``sudo ./PwrDeauther.sh``

**Comment by foxtreat** [comment]
for Future reference, if you get a error about a unexpected bracket on line 25,this fixes it
